version: '3'
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - docker_secrets.env
    volumes:
      - .:/app
      - logs:/app/logs
    links:
      - redis
    networks:
      - altex-network
    container_name: flask
  db:
    image: postgres:12.2
    env_file:
      - docker_secrets.env
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - altex-network
    container_name: postgres_db
  celery:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    command: celery -A web.celery_app:celery worker --loglevel=info
    env_file:
      - docker_secrets.env
    volumes:
      - .:/app
      - logs:/app/logs
      - db:/app/persistence/db
    depends_on:
      - web
      - redis
    networks:
      - altex-network
    container_name: celery
  redis:
    image: 'redis:5.0'
    ports:
      - '6379:6379'
    networks:
      - altex-network
    container_name: redis
networks:
  altex-network:
    driver: bridge
volumes:
  db:
  logs:
