repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["--line-length", "88"]
  - repo: https://github.com/psf/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [--max-line-length=88]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
      - id: autopep8
        args: [--max-line-length=88]
  - repo: https://github.com/pycqa/flake8-annotations
    rev: 20.1.0
    hooks:
      - id: flake8-annotations
  - repo: https://github.com/openai/codeforces-python
    rev: v0.0.7
    hooks:
      - id: codeforces-python
        args: [--length=88]

