"""removed rocket id

Revision ID: 907f52197d5a
Revises: c2aa2bb7625f
Create Date: 2023-02-09 07:35:30.489954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907f52197d5a'
down_revision = 'c2aa2bb7625f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flights_rocket_id_fkey', 'flights', type_='foreignkey')
    op.drop_column('flights', 'rocket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('rocket_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('flights_rocket_id_fkey', 'flights', 'rockets', ['rocket_id'], ['id'])
    # ### end Alembic commands ###
