"""init

Revision ID: c2aa2bb7625f
Revises: 
Create Date: 2023-02-09 07:34:23.102553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2aa2bb7625f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('payload_type', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.Float(), nullable=False),
    sa.Column('orbit', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('customer_type', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=120), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=150), nullable=False),
    sa.Column('launch_date', sa.DateTime(), nullable=False),
    sa.Column('flight_status', sa.String(length=150), nullable=False),
    sa.Column('launch_time', sa.DateTime(), nullable=False),
    sa.Column('launch_site', sa.String(length=150), nullable=False),
    sa.Column('mission_outcome', sa.String(length=150), nullable=False),
    sa.Column('failure_reason', sa.String(length=150), nullable=False),
    sa.Column('landing_type', sa.String(length=150), nullable=False),
    sa.Column('landing_outcome', sa.String(length=150), nullable=False),
    sa.Column('rocket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rocket_id'], ['rockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_table('rockets')
    op.drop_table('customers')
    op.drop_table('cargos')
    # ### end Alembic commands ###
